//
// Created by simone on 21/12/19.
//

#ifndef ELOQUENTARDUINO_MICROMLWAKEWORDIDENTIFICATIONEXAMPLE_INO
#define ELOQUENTARDUINO_MICROMLWAKEWORDIDENTIFICATIONEXAMPLE_INO

#endif //ELOQUENTARDUINO_MICROMLWAKEWORDIDENTIFICATIONEXAMPLE_INO
